Consider a simple linear equation we are trying to find the values of $w$ to maximize $y$:

\begin{equation}
y = w_i x_i, \quad \text{for } i \in \{1, 2, 3, 4, 5, 6\}
\end{equation}

In [1]:
import numpy as np

In [2]:
x = np.array([4, -2, 3.5, 5, -11, -4.7])

num_weights = x.shape[0]
solution_per_population = 8
n_parents = 4

population_size = (solution_per_population, num_weights)
new_population = np.random.uniform(low=-4.0, high=4.0, size=population_size)
new_population.shape

(8, 6)

In [5]:
n_generations = 10  # how many 'epochs'
n_mutations = 2

for generation in range(n_generations):
    print('Generation:', generation)
    
    # Compute fitness
    fitness = np.sum(x * new_population, axis=1)
    
    # Select best parents
    largest_indices = np.argsort(-fitness)[:n_parents]
    parents = np.array([new_population[i] for i in largest_indices])
    print('--------------- Parents ---------------')
    print(parents)
    
    # Crossover to create offspring
    offspring_shape = (new_population.shape[0] - n_parents, num_weights)
    offspring = np.ndarray(offspring_shape)
    crossover_point = offspring_shape[1]//2
    for k in range(offspring_shape[0]):
        parent1_idx = k % parents.shape[0]
        parent2_idx = (k + 1) % parents.shape[0]
    
        # Offspring will have first and second half of genes from first and second parent
        offspring[k, :crossover_point] = parents[parent1_idx, :crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    print('--------------- Offspring ---------------')
    print(offspring)
    
    # Mutation
    mutations_counter = offspring.shape[1] // n_mutations
    for idx in range(offspring.shape[0]):
        gene_idx = mutations_counter - 1
        for mutation_num in range(n_mutations):
            random_value = np.random.uniform(-1.0, 1.0, 1)
            offspring[idx, gene_idx] = offspring[idx, gene_idx] + random_value
            gene_idx = gene_idx + mutations_counter
    print('--------------- Mutated ---------------')
    print(offspring)
    
    # Create new population
    new_population[:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring
    
    print('--------------- New Population ---------------')
    print(new_population,'\n')
    print('Max Sum:', np.max(np.sum(x * new_population, axis=1)))

Generation: 0
--------------- Parents ---------------
[[ 2.8798864   2.04399617 -1.3254904   2.13859124 -4.35069376 -3.72809299]
 [ 3.15233815  2.49893421 -1.73488316  2.13859124 -4.35069376 -3.1929178 ]
 [ 1.05356089  0.53078065 -1.65491959  2.13859124 -4.35069376 -3.77732505]
 [ 1.05356089  0.53078065 -0.542694    2.13859124 -4.35069376 -2.81551292]]
--------------- Offspring ---------------
[[ 2.8798864   2.04399617 -1.3254904   2.13859124 -4.35069376 -3.1929178 ]
 [ 3.15233815  2.49893421 -1.73488316  2.13859124 -4.35069376 -3.77732505]
 [ 1.05356089  0.53078065 -1.65491959  2.13859124 -4.35069376 -2.81551292]
 [ 1.05356089  0.53078065 -0.542694    2.13859124 -4.35069376 -3.72809299]]
--------------- Mutated ---------------
[[ 2.8798864   2.04399617 -1.48047584  2.13859124 -4.35069376 -4.06048636]
 [ 3.15233815  2.49893421 -1.68101527  2.13859124 -4.35069376 -3.71227388]
 [ 1.05356089  0.53078065 -1.04176948  2.13859124 -4.35069376 -3.81218869]
 [ 1.05356089  0.53078065 -0.10627337